### ISSUE TITLE
I apply effects to myself, and I keep getting those lua errors

### ISSUE THREAD

**Issue by Gvbavx** [Aaronek10/SEF#1]
![image](https://github.com/user-attachments/assets/f85e5ef1-66f3-4287-8f13-16f9e4778393)

Only Endurance, Incapacitated and Exposed did work, the others just caused lua errors
I was running gmod in x64 chromium

**Comment by Aaronek10** [comment]
You didnt provided additional arguments.

For ex.
SEF_GiveEffect Healing (nick) 5 2

Applies Healing effect on player for 5 seconds healing 2 HP per 0.3 sec

**Comment by Aaronek10** [comment]
Open this file [with effects](https://github.com/ShadowWolf90/SEF/blob/main/lua/SEF/SEF_EffectList.lua) so you will know what to provide in this console command.
