### ISSUE TITLE
This happens when I apply passives to myself?

### ISSUE THREAD

**Issue by Gvbavx** [Aaronek10/SEF#2]
![image](https://github.com/user-attachments/assets/9b01a1aa-d8fc-4116-95ec-c7b5f8c9f249)
![20240820165646_1](https://github.com/user-attachments/assets/59f17e39-ce86-44d4-bf3d-9a3319a6dfd3)

[[SEF] Status Effect Framework] lua/sef/sef_hud.lua:269: attempt to perform arithmetic on upvalue 'ScaleUI' (a nil value)
  1. v - lua/sef/sef_hud.lua:269
   2. unknown - lua/includes/modules/hook.lua:96

[[SEF] Status Effect Framework] lua/sef/sef_hud.lua:269: attempt to perform arithmetic on upvalue 'ScaleUI' (a nil value)
  1. v - lua/sef/sef_hud.lua:269
   2. unknown - lua/includes/modules/hook.lua:96 (x13)
   
Also passives dIdn't work and display

**Comment by Aaronek10** [comment]
Thanks for reporting.
Issue has been fixed.
