### ISSUE TITLE
Passives don't still work!

### ISSUE THREAD

**Issue by Gvbavx** [Aaronek10/SEF#3]
![20240821083153_1](https://github.com/user-attachments/assets/b49cd8b1-1c4f-46f3-bf45-d6fb5c45e25f)
![20240821083500_1](https://github.com/user-attachments/assets/61190c7b-b638-4dda-b871-9cc4564f80d8)

Iron Skin and Fireborn don't work!!!

Iron Skin doesn't reduce my Received damage by 20%
Fireborn doesn't make me immune to Fire Damage

**Comment by Aaronek10** [comment]
I will take a look at code what i missed once i find some spare time

**Comment by Aaronek10** [comment]
Fixed
