### ISSUE TITLE
bug when i tried to give effect from console

### ISSUE THREAD

**Issue by Mrpurple007** [Aaronek10/SEF#6]
when i write command SEF_GiveEffect exposed кабачочек 1 it gives me a error
[[SEF] Status Effect Framework] lua/sef/sef_functions.lua:583: bad argument #4 to 'format' (number expected, got nil)
  1. format - [C]:-1
   2. unknown - lua/sef/sef_functions.lua:583
    3. unknown - lua/includes/modules/concommand.lua:54

**Comment by Aaronek10** [comment]
Code is correct. This is caused by wrong typing, nonstandard symbols or wrong usage of command.

**Comment by Mrpurple007** [comment]
hmm maybe i type russian
can i type steamid instead of nickname
