### ISSUE TITLE
Another error when I apply passives to myself...

### ISSUE THREAD

**Issue by Gvbavx** [Aaronek10/SEF#7]
This happened when I apply passives to myself

[[SEF] Status Effect Framework] lua/sef/sef_hooks.lua:50: attempt to call field 'Function' (a nil value)
    1. v - lua/sef/sef_hooks.lua:50
        2. unknown - lua/includes/modules/hook.lua:96

**Comment by Aaronek10** [comment]
I will check it out

**Comment by Gvbavx** [comment]
Oh it still happened
![20240918212813_1](https://github.com/user-attachments/assets/88a772d5-56fc-473a-b8ad-9ca0983da25e)

![image](https://github.com/user-attachments/assets/3b5b7e23-6f76-4465-9312-a61f46134491)
